# Generated by Django 2.0.6 on 2018-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0005_auto_20180719_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
