# Generated by Django 2.0.6 on 2018-07-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwc', '0007_auto_20180719_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
    ]
